#!/usr/bin/env bash
name="libevdev"
version="1.13.1"
description="Wrapper library for evdev devices"
source="https://gitlab.freedesktop.org/libevdev/libevdev/-/archive/libevdev-$version/libevdev-libevdev-$version.tar.gz"
depends=""
builddepend="doxygen,meson,python3"
group="sys.libs"

setup(){
cd $SOURCEDIR
meson setup $BUILDDIR \
--prefix=/usr \
--libdir=/usr/lib \
-Db_lto=true \
-Dtests=disabled \
-Ddocumentation=enabled \
-Dcoverity=false
}
build(){
ninja -C $BUILDDIR
}
package(){
DESTDIR=$DESTDIR ninja -C $BUILDDIR install
}
