#!/usr/bin/env bash
name="glib"
version="2.78.0"
description="Low-level core library that forms the basis for projects\
such as GTK+ and GNOME."
source="https://download.gnome.org/sources/glib/2.78/glib-${version}.tar.xz"
depends="bzip2,gettext,python,py3-packaging"
builddepend="bison,flex,libffi,meson,pcre2,py3-setuptools,py3-docutils,util-linux"
group="dev.libs"
setup(){
cp -prfv $PACKAGEDIR/files/* $SOURCEDIR
cd $SOURCEDIR
meson setup $BUILDDIR --prefix=/usr \
--libdir=/usr/lib64 \
--default-library both \
-D glib_debug=disabled \
-D selinux=disabled \
-D sysprof=disabled
}
build(){
ninja -C $BUILDDIR
}
package(){
DESTDIR=$DESTDIR ninja -C $BUILDDIR install
}
