#!/bin/sh
#set -ex
mkdir /output -p
mkdir -p /klysource
>index.lst
find * -type f -name *.kly |
			while IFS= read file_name; do
					dosya="$(dirname $file_name)/klybuild"
					version=$(cat $dosya|grep version=)
					name=$(cat $dosya|grep name=)
					depends=$(cat $dosya|grep depends=)
					echo "$name|$version|$depends|$(dirname $file_name)">>index.lst
			done
cp -rf index.lst /output
# *****************************source files******************************
cp -prfv ./* /klysource/
find /klysource/* -type f -name *.kly |
			while IFS= read file_name; do
				rm -rf "$file_name"
			done
tar -cf /output/klysourcepackage.tar /klysource/
rm -rf /klysource
