#!/bin/bash
sed -i "/messagebus/d" /etc/group
sed -i "/messagebus/d" /etc/passwd

echo "messagebus:x:109:" >> /etc/group
echo "messagebus:x:103:109::/nonexistent:/usr/sbin/nologin" >>/etc/passwd


if [ ! -f /etc/machine-id ] ; then
    dbus-uuidgen --ensure=/etc/machine-id
fi
if busybox ls /bin/su -la | grep "^...s" >/dev/null ; then
    chmod 4755 /usr/libexec/dbus-daemon-launch-helper
fi
dbus-send --system --type=method_call --dest=org.freedesktop.DBus / \
	org.freedesktop.DBUS.ReloadConfig >/dev/null 2>&1 || :

# servis işlemleri 
rc-service dbus start
