#!/usr/bin/env bash
name="xf86-video-nouveau"
version="1.0.17"
description="Accelerated Open Source driver for nVidia cards"
source="https://gitlab.freedesktop.org/xorg/driver/xf86-video-nouveau/-/archive/\
xf86-video-nouveau-$version/xf86-video-nouveau-xf86-video-nouveau-$version.tar.gz"
depends=""
group="x11.drivers"
setup(){
cp -prfv $PACKAGEDIR/files/* $SOURCEDIR/
cd $SOURCEDIR
patch -Np1 < ./xorg-server-21.1.diff
autoreconf -fvi
./configure --prefix=/usr \
--libdir=/usr/lib64/
}
build(){
make
}
package(){
make install DESTDIR=$DESTDIR
}
