#!/usr/bin/env bash
name="libxshmfence"
version="1.3.2"
description="Shared memory fences using futexes"
source="https://www.x.org/archive/individual/lib/libxshmfence-$version.tar.xz"
depends="xorgproto"
group="x11.libs"
setup(){
$SOURCEDIR/configure --prefix=/usr \
--libdir=/usr/lib64/
}
build(){
make
}
package(){
make install DESTDIR=$DESTDIR
}
