#!/usr/bin/env bash
name="xf86-video-r128"
version="6.12.1"
description="ATI Rage128 video drive"
source="https://gitlab.freedesktop.org/xorg/driver/xf86-video-r128/-/archive/\
xf86-video-r128-$version/xf86-video-r128-xf86-video-r128-$version.tar.gz"
depends=""
group="x11.drivers"
setup(){
cd $SOURCEDIR
./autogen.sh
./configure --prefix=/usr \
--libdir=/usr/lib64/
}
build(){
make
}
package(){
make install DESTDIR=$DESTDIR
}
