#!/usr/bin/env bash
name="xcb-util"
version="0.4.0"
description="X C-language Bindings sample implementations"
source="https://www.x.org/releases/individual/xcb/xcb-util-${version}.tar.gz"
depends="libxcb,util-macros,xorgproto"
group="x11.libs"
setup(){
$SOURCEDIR/configure --prefix=/usr \
--libdir=/usr/lib64 \
--enable-shared \
--enable-static \
--disable-devel-docs \
--without-doxygen
}
build(){
make
}
package(){
make install DESTDIR=$DESTDIR
}
