#!/usr/bin/env bash
name="libXmu"
version="1.1.4"
description="X.Org Xmu library"
source="https://www.x.org/archive/individual/lib/libXmu-$version.tar.xz"
depends="libXt,libXext,libX11"
group="x11.libs"
setup(){
$SOURCEDIR/configure --prefix=/usr \
--libdir=/usr/lib64/
}
build(){
make
}
package(){
make install DESTDIR=$DESTDIR
}
