#!/usr/bin/env bash
name="libxkbfile"
version="1.1.2"
description="X.Org xkbfile library"
source="https://www.x.org/archive/individual/lib/libxkbfile-$version.tar.gz"
depends="libX11,xorgproto"
group="x11.libs"
setup(){
$SOURCEDIR/configure --prefix=/usr \
--libdir=/usr/lib64/
}
build(){
make
}
package(){
make install DESTDIR=$DESTDIR
}
