#!/usr/bin/env bash
name="libXfixes"
version="6.0.0"
description="X.Org Xfixes library"
source="https://www.x.org/archive/individual/lib/libXfixes-$version.tar.gz"
depends=""
group="x11.libs"
setup(){
$SOURCEDIR/configure --prefix=/usr \
--libdir=/usr/lib64/
}
build(){
make
}
package(){
make install DESTDIR=$DESTDIR
}
