#!/usr/bin/env bash
name="libX11"
version="1.8"
description="X.Org X11 library"
source="https://www.x.org/archive/individual/lib/libX11-$version.tar.xz"
depends="libxcb,libXau,libXdmcp,xtrans"
group="x11.libs"
setup(){
$SOURCEDIR/configure --prefix=/usr \
--libdir=/usr/lib64/
}
build(){
make
}
package(){
make install DESTDIR=$DESTDIR
}
