#!/usr/bin/env bash
name="libICE"
version="1.1.1"
description="X.Org Inter-Client Exchange library"
source="https://www.x.org/archive/individual/lib/libICE-$version.tar.xz"
depends="xorgproto"
group="x11.libs"
setup(){
$SOURCEDIR/configure --prefix=/usr \
--libdir=/usr/lib64/
}
build(){
make
}
package(){
make install DESTDIR=$DESTDIR
}
