#!/usr/bin/env bash
name="xkbcomp"
version="1.4.6"
description="XKB keyboard description compiler"
source="https://gitlab.freedesktop.org/xorg/app/xkbcomp/-/archive/\
xkbcomp-$version/xkbcomp-xkbcomp-$version.tar.gz"
depends="libxkbfile,libX11"
group="x11.apps"
setup(){
cd $SOURCEDIR
autoreconf -fvi
./configure --prefix=/usr \
--libdir=/usr/lib64/
}
build(){
make
}
package(){
make install DESTDIR=$DESTDIR
}
