#!/usr/bin/env bash
name="libXrandr"
version="1.5.3"
description="X.Org Xrandr library"
source="https://www.x.org/archive/individual/lib/libXrandr-$version.tar.xz"
depends="libXrender"
group="x11.libs"
setup(){
$SOURCEDIR/configure --prefix=/usr \
--libdir=/usr/lib64/
}
build(){
make
}
package(){
make install DESTDIR=$DESTDIR
}
