#!/usr/bin/env bash
name="libXpm"
version="3.5.14"
description="X.Org Xpm library"
source="https://www.x.org/archive/individual/lib/libXpm-$version.tar.xz"
depends="libX11"
group="x11.libs"
setup(){
$SOURCEDIR/configure --prefix=/usr \
--libdir=/usr/lib64/
}
build(){
make
}
package(){
make install DESTDIR=$DESTDIR
}
