#!/usr/bin/env bash
name="fribidi"
version="1.0.12"
description="A free implementation of the unicode bidirectional algorithm"
source="https://github.com/fribidi/fribidi/releases/download/\
v$version/fribidi-$version.tar.xz"
depends=""
builddepend="meson"
group="dev.libs"
setup(){
cd $SOURCEDIR
./configure --prefix=/usr \
--libdir=/usr/lib64/
}
build(){
make
}
package(){
make install DESTDIR=$DESTDIR
}
