#!/usr/bin/env bash
name="libpciaccess"
version="0.17"
description="Library providing generic access to the PCI bus and devices"
source="https://www.x.org/archive/individual/lib/libpciaccess-$version.tar.xz"
depends=""
group="x11.libs"
setup(){
$SOURCEDIR/configure --prefix=/usr \
--libdir=/usr/lib64/
}
build(){
make
}
package(){
make install DESTDIR=$DESTDIR
}
