#!/usr/bin/env bash
name="libXau"
version="1.0.11"
description="X.Org X authorization library"
source="https://www.x.org/releases/individual/lib/libXau-${version}.tar.xz"
depends="xorgproto"
builddepend=""
group="x11.libs"
setup(){
export PKG_CONFIG_PATH=/usr/lib/pkgconfig
cd $SOURCEDIR
./configure --prefix=/usr \
--sysconfdir=/etc \
--without-xproto
}
build(){
make
}
package(){
make install DESTDIR=$DESTDIR
}
