#!/usr/bin/env bash
name="libthai"
version="0.1.29"
description="Package libthai"
source="https://github.com/tlwg/libthai/releases/download/\
v$version/libthai-$version.tar.xz"
depends="libdatrie"
group="x11.libs"
setup(){
$SOURCEDIR/configure --prefix=/usr \
--libdir=/usr/lib64 \
--disable-dict
}
build(){
make
}
package(){
make install DESTDIR=$DESTDIR
}
