#!/usr/bin/env bash
name="libXrender"
version="0.9.11"
description="X.Org Xrender library"
source="https://www.x.org/archive/individual/lib/libXrender-$version.tar.xz"
depends=""
group="x11.libs"
setup(){
$SOURCEDIR/configure --prefix=/usr \
--libdir=/usr/lib64/
}
build(){
make
}
package(){
make install DESTDIR=$DESTDIR
}
